all:
    children:
        InfoSeclab:
            hosts:
#                slkbCentOS1:
#                    ansible_host: 192.168.56.2
                slkbCentOS2:
                    ansible_host: 192.168.56.3
                    ansible_user: asb