---

# keygen, upload to 
- openssh_keypair:
  path: ~/.ssh/id_"{{ host_key_algorithms }}"
  type: "{{ host_key_algorithms }}"

- name: Read SSH public key to authorize
  shell: cat ~/.ssh/id_"{{ host_key_algorithms }}".pub
  register: ssh_pub_key

- name: Authorize key with GitHub
  local_action:
    module: github_key
    name: Access Key for Some Machine
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'

   