---
- name: Remove unsafe public-key cryptosystems
  replace:
    path: "{{ sshd_config_path }}"
    regexp: '^HostKey \/etc\/ssh\/ssh_host_ecdsa_key$'
    replace: '#HostKey /etc/ssh/ssh_host_ecdsa_key'
  become: yes
  register: sshd_config_updated

- name: restart sshd if new version is deployed
  service:
    name: sshd
    state: restarted
  when: sshd_config_updated.changed
  become: yes
...