---
- name: Remove unsafe public-key cryptosystems
  lineinfile:
    path: "{{ sshd_config_path }}"
    validate: /usr/sbin/sshd -t
    state: present
    regexp: '^HostKey \/etc\/ssh\/ssh_host_ecdsa_key$'
    backup: yes
    line: '^#HostKey \/etc\/ssh\/ssh_host_ecdsa_key$'
...